USE SQL_PROJECT_1;
SELECT * FROM RETAIL_SALES;

---- Checking if any null values are there in the table?

SELECT * FROM RETAIL_SALES WHERE 
  TRANSACTIONS_ID IS NULL
  OR
  SALE_DATE IS NULL
  OR
  SALE_TIME IS NULL
  OR
  CUSTOMER_ID IS NULL
  OR
  GENDER IS NULL
  OR
  AGE IS NULL
  OR
  CATEGORY IS NULL
  OR
  QUANTIY IS NULL
  OR
  PRICE_PER_UNIT IS NULL
  OR
  COGS IS NULL
  OR
  TOTAL_SALE IS NULL;
  
  SELECT * FROM RETAIL_SALES;
  
  SELECT COUNT(DISTINCT CATEGORY) FROM RETAIL_SALES; 
  
  --- 1.WRITE A SQL QUERY TO RETRIEVE ALL COLUMNS FOR SALES MADE ON '2022-11-05'?
  
  SELECT * FROM RETAIL_SALES WHERE SALE_DATE='2022-11-05';
  
  ---- 2.WRITE A SQL QUERY TO RETRIEVE ALL TRANSACTIONS WHERE THE CATEGORY IS 'CLOTHING' AND THE QUANTITY SOLD IS MORE THAN 10 IN THE MONTH OF NOVEMBER 2022;
  
SELECT *
FROM RETAIL_SALES
WHERE CATEGORY = 'CLOTHING'
  AND QUANTIY >= 2
  AND YEAR(SALE_DATE) = 2000
  AND MONTH(SALE_DATE) = 11;
  
  ----- 3.WRITE A SQL QUERY TO CALCULATE THE TOTAL SALES FRO EACH CATEGORY?
  
  SELECT CATEGORY, 
  SUM(TOTAL_SALE) AS TOTAL_SALES,
  COUNT(*) AS TOTAL_ORDERS FROM 
  RETAIL_SALES 
  GROUP BY CATEGORY;
  
  --- 4.WRITE A SQL QUERY TO FIND THE AVERAGE AGE OF CUSTOMERS WHO PURCHASED ITEMS FROM THE 'BEAUTY' CATEGORY?
  
  SELECT CATEGORY, AVG(AGE) AS AVERAGE_AGE, 
  COUNT(*) AS TOTAL_SALES 
  FROM 
  RETAIL_SALES 
  WHERE CATEGORY='BEAUTY';
  
  ---- 5.WRITE A SQL QUERY TO FIND ALL TRANSACTIONS WHERE THE TOTAL_SALES IS GREATER THAN 1000?
  
  SELECT * FROM 
  RETAIL_SALES 
  WHERE TOTAL_SALE>1000;
  
  ---- 6.WRITE A SQL QUERY TO FIND THE TOTAL NUMBER OF TRANSACTIONS MADE BY EACH GENDER IN EACH CATEGORY ?
  
  SELECT CATEGORY, GENDER, COUNT(*) AS TOTAL_SALES
  FROM RETAIL_SALES
  GROUP BY CATEGORY, GENDER ORDER BY CATEGORY;

---- 7. WRITE A SQL QUERY TO CALCULATE THE AVERAGE SALE FOR EACH MONTH. fIND OUT BEST SELLING MONTH IN EACH YEAR?

SELECT
* FROM
(
SELECT
YEAR(SALE_DATE) AS SALES_YEAR,
MONTH(SALE_DATE)AS SALES_MONTH,
ROUND(AVG(TOTAL_SALE),2) AS AVERAGE_SALES,
RANK() OVER(PARTITION BY YEAR(SALE_DATE)
ORDER BY AVG(TOTAL_SALE) DESC) AS RANK_NUMBER
FROM RETAIL_SALES
GROUP BY YEAR(SALE_DATE), MONTH(SALE_DATE)
) 
AS T1 WHERE RANK_NUMBER  =1;

---- 8. WRITE A SQL QUERY TO FIND THE TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL SALES?

SELECT 
	CUSTOMER_ID,
    SUM(TOTAL_SALE) AS TOTAL_SALE
    FROM
    RETAIL_SALES GROUP BY CUSTOMER_ID ORDER BY TOTAL_SALE DESC  LIMIT 5;

---- 9. WRITE A SQL QUERY TO FIND THE NUMBER OF UNIQUE CUSTOMERS WHO PURCHASED ITEMS FROM EACH CATEGORY?

SELECT 
   COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
   CATEGORY FROM RETAIL_SALES 
   GROUP BY CATEGORY;
   
--- 10> WRITE A SQL QUERY TO CREATE EACH SHIFT AND NO.OF ORDERS ?( EX: EARLY MORNING <=12, AFTERNOON BETWEEN 12&17, EVENING>17).
SELECT * FROM RETAIL_SALES;

WITH HOURLY_SALE
AS
(
SELECT *,
		CASE
			WHEN HOUR(SALE_TIME) <12 THEN 'MORNING'
            WHEN HOUR(SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
            ELSE 'EVENING'
		END AS SHIFT
	FROM RETAIL_SALES
)
SELECT SHIFT,
COUNT(TRANSACTIONS_ID) AS TOTAL_ORDERS FROM HOURLY_SALE
GROUP BY SHIFT;
	
	
